"""domain-chip-memory package."""

from .sdk import (
    AnswerExplanationRequest,
    CurrentStateRequest,
    EventRetrievalRequest,
    EvidenceRetrievalRequest,
    HistoricalStateRequest,
    MemoryMaintenanceResult,
    MemoryWriteRequest,
    SparkMemorySDK,
    build_sdk_contract_summary,
    build_sdk_maintenance_replay_contract_summary,
)
from .spark_shadow import (
    build_telegram_shadow_adapter_contract_summary,
    SparkShadowIngestAdapter,
    SparkShadowIngestRequest,
    SparkShadowReport,
    SparkShadowProbe,
    SparkShadowTurn,
    build_builder_shadow_adapter_contract_summary,
    build_shadow_report,
    build_shadow_ingest_contract_summary,
    build_shadow_replay_contract_summary,
    normalize_builder_shadow_export_payload,
    normalize_telegram_bot_export_payload,
    validate_shadow_replay_payload,
)
from .spark_integration import build_spark_integration_contract_summary
from .spark_kb import build_spark_kb_contract_summary, build_spark_kb_health_report, scaffold_spark_knowledge_base
from .memory_sidecars import (
    DisabledMemorySidecarAdapter,
    MemorySidecarEpisode,
    MemorySidecarHealthResult,
    MemorySidecarHit,
    MemorySidecarRetrievalRequest,
    MemorySidecarRetrievalResult,
    MemorySidecarShadowComparison,
    MemorySidecarUpsertResult,
    build_memory_sidecar_contract_summary,
)

__all__ = [
    "__version__",
    "SparkMemorySDK",
    "MemoryWriteRequest",
    "MemoryMaintenanceResult",
    "CurrentStateRequest",
    "HistoricalStateRequest",
    "EvidenceRetrievalRequest",
    "EventRetrievalRequest",
    "AnswerExplanationRequest",
    "build_sdk_contract_summary",
    "build_sdk_maintenance_replay_contract_summary",
    "SparkShadowIngestAdapter",
    "SparkShadowTurn",
    "SparkShadowIngestRequest",
    "SparkShadowProbe",
    "SparkShadowReport",
    "normalize_builder_shadow_export_payload",
    "normalize_telegram_bot_export_payload",
    "build_builder_shadow_adapter_contract_summary",
    "build_telegram_shadow_adapter_contract_summary",
    "build_shadow_report",
    "build_shadow_ingest_contract_summary",
    "build_shadow_replay_contract_summary",
    "validate_shadow_replay_payload",
    "build_spark_integration_contract_summary",
    "build_spark_kb_contract_summary",
    "build_spark_kb_health_report",
    "scaffold_spark_knowledge_base",
    "DisabledMemorySidecarAdapter",
    "MemorySidecarEpisode",
    "MemorySidecarHealthResult",
    "MemorySidecarHit",
    "MemorySidecarRetrievalRequest",
    "MemorySidecarRetrievalResult",
    "MemorySidecarShadowComparison",
    "MemorySidecarUpsertResult",
    "build_memory_sidecar_contract_summary",
]
__version__ = "0.1.0"
